//
// Created by youni on 22-7-24.
//

#ifndef CREACTOR_EXAMPLE_PROTOBUF_DISPATCHER_H_
#define CREACTOR_EXAMPLE_PROTOBUF_DISPATCHER_H_

class Dispatcher {

};

#endif //CREACTOR_EXAMPLE_PROTOBUF_DISPATCHER_H_
